# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
