# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category',
            new_name='categories',
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
